name: Frontend (Expo) CI

on:
  push:
    paths: ["frontend/**", ".github/workflows/frontend.yml"]
  pull_request:
    paths: ["frontend/**", ".github/workflows/frontend.yml"]

jobs:
  frontend-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install deps
        working-directory: frontend
        run: |
          npm ci || npm install
      - name: Typecheck (TS)
        working-directory: frontend
        run: npx tsc --noEmit
